### ISSUE TITLE
bug(kosko@1.1.2): ERR_PACKAGE_PATH_NOT_EXPORTED on kosko bin

### ISSUE THREAD

**Issue by douglasduteil** [tommy351/kosko#65]
Hi @tommy351 

It seems like your latest kosko bin can't be access from the `kosko` package

<details>
	<summary>
	  $ yarn global add kosko@1.1.2 kubernetes-models@1.5.2 && $(yarn global bin)/kosko --verion
	</summary>

```sh
gitpod /workspace/kosko $ yarn global add kosko@1.1.2 kubernetes-models@1.5.2
yarn global v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...[4/4] Building fresh packages...

success Installed "kosko@1.1.2" with binaries:
      - kosko
warning "kubernetes-models@1.5.2" has no binaries
Done in 11.33s.
gitpod /workspace/kosko $ $(yarn global bin)/kosko --verion
internal/modules/cjs/loader.js:438
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './bin/kosko.js' is not defined by "exports" in /home/gitpod/.config/yarn/global/node_module
s/@kosko/cli/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/gitpod/.config/yarn/global/node_modules/kosko/bin/kosko.js:6:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
gitpod /workspace/kosko $ 

```
</details>

Same on a local installation 

<details>
	<summary>
	  $ yarn add -D kosko kubernetes-models && yarn kosko --version
	</summary>

```
gitpod /tmp $ npm init -y
Wrote to /tmp/package.json:

{
  "name": "tmp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


npm notice 
npm notice New minor version of npm available! 7.5.6 -> 7.6.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.6.2
npm notice Run npm install -g npm@7.6.2 to update!
npm notice 
gitpod /tmp $ yarn add -D kosko kubernetes-models
yarn add v1.22.10
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 103 new dependencies.
info Direct dependencies
├─ kosko@1.1.2
└─ kubernetes-models@1.5.2
info All dependencies
├─ @iarna/toml@2.2.5
├─ @kosko/cli@1.2.2
├─ @kosko/config@1.0.4
├─ @kosko/generate@1.1.0
├─ @kosko/migrate@2.0.0
├─ @kosko/yaml@1.0.0
├─ @kubernetes-models/base@1.5.2
├─ @nodelib/fs.scandir@2.1.4
├─ @nodelib/fs.stat@2.0.4
├─ @nodelib/fs.walk@1.2.6
├─ ajv@6.12.6
├─ ansi-regex@5.0.0
├─ ansi-styles@4.3.0
├─ argparse@2.0.1
├─ at-least-node@1.0.0
├─ braces@3.0.2
├─ camelcase@6.2.0
├─ chalk@4.1.0
├─ clean-stack@3.0.1
├─ cliui@7.0.4
├─ color-convert@2.0.1
├─ color-name@1.1.4
├─ deep-is@0.1.3
├─ emoji-regex@8.0.0
├─ error-ex@1.3.2
├─ escalade@3.1.1
├─ escodegen@1.14.3
├─ esprima@1.2.2
├─ estraverse@4.3.0
├─ esutils@2.0.3
├─ exit@0.1.2
├─ fast-deep-equal@3.1.3
├─ fast-glob@3.2.5
├─ fast-json-stable-stringify@2.1.0
├─ fast-levenshtein@2.0.6
├─ fastq@1.11.0
├─ figures@2.0.0
├─ fill-range@7.0.1
├─ find-up@4.1.0
├─ function-bind@1.1.1
├─ get-caller-file@2.0.5
├─ get-stdin@8.0.0
├─ glob-parent@5.1.2
├─ graceful-fs@4.2.6
├─ has-flag@4.0.0
├─ has@1.0.3
├─ is-arrayish@0.2.1
├─ is-core-module@2.2.0
├─ is-extglob@2.1.1
├─ is-fullwidth-code-point@3.0.0
├─ is-glob@4.0.1
├─ is-number@7.0.0
├─ is-plain-object@5.0.0
├─ json-parse-better-errors@1.0.2
├─ json-schema-traverse@0.4.1
├─ jsonfile@6.1.0
├─ jsonpath@1.1.0
├─ kosko@1.1.2
├─ kubernetes-models@1.5.2
├─ levn@0.3.0
├─ load-json-file@4.0.0
├─ locate-path@5.0.0
├─ make-dir@3.1.0
├─ merge2@1.4.1
├─ micromatch@4.0.2
├─ ms@2.1.2
├─ node-fetch@2.6.1
├─ optionator@0.8.3
├─ p-limit@2.3.0
├─ p-locate@4.1.0
├─ p-try@2.2.0
├─ parse-json@4.0.0
├─ path-exists@4.0.0
├─ path-parse@1.0.6
├─ picomatch@2.2.2
├─ pify@3.0.0
├─ pkg-conf@2.1.0
├─ pkg-dir@4.2.0
├─ punycode@2.1.1
├─ queue-microtask@1.2.2
├─ require-directory@2.1.1
├─ resolve-cwd@3.0.0
├─ resolve-from@5.0.0
├─ resolve@1.20.0
├─ reusify@1.0.4
├─ run-parallel@1.2.0
├─ semver@6.3.0
├─ signale@1.4.0
├─ source-map@0.6.1
├─ static-eval@2.0.2
├─ string-width@4.2.2
├─ strip-bom@3.0.0
├─ superstruct@0.14.2
├─ supports-color@7.2.0
├─ to-regex-range@5.0.1
├─ type-fest@0.20.2
├─ underscore@1.7.0
├─ uri-js@4.4.1
├─ word-wrap@1.2.3
├─ wrap-ansi@7.0.0
├─ y18n@5.0.5
├─ yargs-parser@20.2.6
└─ yargs@16.2.0
Done in 3.00s.
gitpod /tmp $ cat package.json 
{
  "name": "tmp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "kosko": "^1.1.2",
    "kubernetes-models": "^1.5.2"
  }
}
gitpod /tmp $ yarn kosko --version
yarn run v1.22.10
$ /tmp/node_modules/.bin/kosko --version
internal/modules/cjs/loader.js:438
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './bin/kosko.js' is not defined by "exports" in /tmp/node_modules/@kosko/cli/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/node_modules/kosko/bin/kosko.js:6:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
gitpod /tmp $ 
```
</details>

We have a 

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './bin/kosko.js' is not defined by "exports" in /home/gitpod/.config/yarn/global/node_module
```

**Should we use `@kosko/cli` for now one ? It it a breaking change ?**

<details>
	<summary>
	  $ yarn add -D @kosko/cli kubernetes-models && $yarn kosko --verion
	</summary>

```sh
gitpod ~ $ mktemp -d
/tmp/tmp.B2eR3pudS1
gitpod ~ $ 
gitpod ~ $ cd /tmp/tmp.B2eR3pudS1
gitpod /tmp/tmp.B2eR3pudS1 $ npm init -y
Wrote to /tmp/tmp.B2eR3pudS1/package.json:

{
  "name": "tmp.B2eR3pudS1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


gitpod /tmp/tmp.B2eR3pudS1 $ yarn add -D @kosko/cli kubernetes-models
yarn add v1.22.10
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved lockfile.
success Saved 103 new dependencies.
info Direct dependencies
├─ @kosko/cli@1.2.2
└─ kubernetes-models@1.5.2
info All dependencies
├─ @iarna/toml@2.2.5
├─ @kosko/cli@1.2.2
├─ @kosko/config@1.0.4
├─ @kosko/generate@1.1.0
├─ @kosko/migrate@2.0.0
├─ @kosko/yaml@1.0.0
├─ @kubernetes-models/base@1.5.2
├─ @nodelib/fs.scandir@2.1.4
├─ @nodelib/fs.stat@2.0.4
├─ @nodelib/fs.walk@1.2.6
├─ ajv@6.12.6
├─ ansi-regex@5.0.0
├─ ansi-styles@4.3.0
├─ argparse@2.0.1
├─ at-least-node@1.0.0
├─ braces@3.0.2
├─ camelcase@6.2.0
├─ chalk@4.1.0
├─ clean-stack@3.0.1
├─ cliui@7.0.4
├─ color-convert@2.0.1
├─ color-name@1.1.4
├─ deep-is@0.1.3
├─ emoji-regex@8.0.0
├─ error-ex@1.3.2
├─ escalade@3.1.1
├─ escodegen@1.14.3
├─ esprima@1.2.2
├─ estraverse@4.3.0
├─ esutils@2.0.3
├─ exit@0.1.2
├─ fast-deep-equal@3.1.3
├─ fast-glob@3.2.5
├─ fast-json-stable-stringify@2.1.0
├─ fast-levenshtein@2.0.6
├─ fastq@1.11.0
├─ figures@2.0.0
├─ fill-range@7.0.1
├─ find-up@2.1.0
├─ function-bind@1.1.1
├─ get-caller-file@2.0.5
├─ get-stdin@8.0.0
├─ glob-parent@5.1.2
├─ graceful-fs@4.2.6
├─ has-flag@4.0.0
├─ has@1.0.3
├─ import-local@3.0.2
├─ is-arrayish@0.2.1
├─ is-core-module@2.2.0
├─ is-extglob@2.1.1
├─ is-fullwidth-code-point@3.0.0
├─ is-glob@4.0.1
├─ is-number@7.0.0
├─ is-plain-object@5.0.0
├─ json-parse-better-errors@1.0.2
├─ json-schema-traverse@0.4.1
├─ jsonfile@6.1.0
├─ jsonpath@1.1.0
├─ kubernetes-models@1.5.2
├─ levn@0.3.0
├─ load-json-file@4.0.0
├─ locate-path@2.0.0
├─ make-dir@3.1.0
├─ merge2@1.4.1
├─ micromatch@4.0.2
├─ ms@2.1.2
├─ node-fetch@2.6.1
├─ optionator@0.8.3
├─ p-limit@1.3.0
├─ p-locate@2.0.0
├─ p-try@1.0.0
├─ parse-json@4.0.0
├─ path-exists@4.0.0
├─ path-parse@1.0.6
├─ picomatch@2.2.2
├─ pify@3.0.0
├─ pkg-conf@2.1.0
├─ pkg-dir@4.2.0
├─ punycode@2.1.1
├─ queue-microtask@1.2.2
├─ require-directory@2.1.1
├─ resolve-cwd@3.0.0
├─ resolve-from@5.0.0
├─ resolve@1.20.0
├─ reusify@1.0.4
├─ run-parallel@1.2.0
├─ semver@6.3.0
├─ signale@1.4.0
├─ source-map@0.6.1
├─ static-eval@2.0.2
├─ string-width@4.2.2
├─ strip-bom@3.0.0
├─ superstruct@0.14.2
├─ supports-color@7.2.0
├─ to-regex-range@5.0.1
├─ type-fest@0.20.2
├─ underscore@1.7.0
├─ uri-js@4.4.1
├─ word-wrap@1.2.3
├─ wrap-ansi@7.0.0
├─ y18n@5.0.5
├─ yargs-parser@20.2.6
└─ yargs@16.2.0
Done in 3.07s.
gitpod /tmp/tmp.B2eR3pudS1 $ yarn kosko --version
yarn run v1.22.10
$ /tmp/tmp.B2eR3pudS1/node_modules/.bin/kosko --version
1.2.2
Done in 0.25s.
```

</details>

**Comment by tommy351** [comment]
Thanks, this issue will be fixed in the next version.
